
name: HiSatwinder
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload APK to GitHub Releases
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.repository.releases_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: app-debug-${{ github.run_id }}.apk
          asset_content_type: application/vnd.android.package-archive

  print-download-url:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get APK Download URL
        id: get-download-url
        run: echo "::set-output name=apk_url::$(jq -r '.browser_download_url' $GITHUB_EVENT_PATH)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_API_URL: https://api.github.com/repos/${{ github.repository }}/releases/latest

      - name: Output APK Download URL
        run: echo "APK Download URL: ${{ steps.get-download-url.outputs.apk_url }}"





